mas "1Password 7 - Password Manager", id: 1333542190
mas "Tailscale", id: 1475387142
mas "Motion", id: 434290957
mas "Swift Playgrounds", id: 1496833156
mas "Wireguard", id: 1451685025
mas "Final Cut Pro", id: 424389933
mas "Logic Pro X", id: 634148309
mas "1Blocker For Safari", id: 1107421413
mas "Xcode", id: 497799835
mas "Pixelmator Pro", id: 1289583905

tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "hybridgroup/tools"
tap "stripe/stripe-cli"
brew "ack"
brew "gdbm"
brew "readline"
brew "xz"
brew "b2-tools"
brew "bison"
brew "libffi"
brew "cmake"
brew "dfu-util"
brew "libksba"
brew "pth"
brew "exif"
brew "exiftool"
brew "git"
brew "git-lfs"
brew "gmp"
brew "pinentry"
brew "gnupg"
brew "gphoto2"
brew "hugo"
brew "jq"
brew "ledger"
brew "libyaml"
brew "lynx"
brew "nghttp2"
brew "ninja"
brew "pinentry-mac"
brew "protobuf"
brew "qrencode"
brew "reattach-to-user-namespace"
brew "redis"
brew "rust"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watch", link: false
brew "watchman"
brew "wget"
brew "xpdf"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "github/gh/gh"
brew "heroku/brew/heroku"
brew "stripe/stripe-cli/stripe"

cask "firefox"
cask "google-chrome"
cask "docker"
cask "postgres"
cask "basecamp"
cask "carbon-copy-cloner"
cask "netnewswire"
cask "sf-symbols"
cask "retrobatch"
